services:
    app:
        build: Dockerfile
        volumes:
            - .:./workspace
        depends_on:
            - redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"    
 