services:
    app:
        image: sciabarracom/mastrogpt-starter:2501041930
        volumes:
            - .:./workspace
        depends_on:
            - redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"    
 